http:
  port: 9856
server:
  port: 443
  ssl:
    key-store: classpath:ty0818.cn.pfx
    key-store-password: cb2hvk79z9
    keyStoreType: PKCS12
  tomcat:
    max-http-header-size: 8096
spring:
  datasource:
    url: jdbc:mysql://cdb-7mn3hyv4.bj.tencentcdb.com:10012/trace?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Qwer123456

###########分页###########

logging:
  config: classpath:config/log4j2-dev.xml
  level:
    root: debug
file:
  img: file:D:/Photos/img/
wx:
  miniapp:
    configs:
      - appid: wxd4afc938daf69afe
        appName: mingmeiyouji
        secret: fc0d7b1bd39b66ad67defe3cb26138b0
        token: Qwer123456
        aesKey: Pp4XuVLSY01gLoc1Y05mxHuU9FFXFPV9ZfC5iFA4xlY
        msgDataFormat: JSON