server:
  port: 9866
  tomcat:
    max-http-header-size: 8096
spring:
  datasource:

###########分页###########

logging:
  config: classpath:config/log4j2-dev.xml
  level:
    root: debug
file:
  img: file:D:/Photos/img/