mybatis:
  config-location: classpath:config/sqlMapConfig.xml
  type-aliases-package: com.tangyuan.blog.dal.com.tangyuan.trace.entity
  mapper-locations:    classpath:config/mapper/*Mapper.xml
spring:
  profiles:
    active: dev
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql