server:
  port: 9856
  tomcat:
    max-http-header-size: 8096
spring:
  datasource:
    url:
    username:
    password:

###########分页###########

logging:
  config: classpath:config/log4j2-dev.xml
  level:
    root: debug
file:
  img: file:D:/Photos/img/
wx:
  miniapp:
    configs:
      - appid:
        appName:
        secret:
        token:
        aesKey:
        msgDataFormat: